# Background and foreground colors
background = #000000
foreground = #e6e6e6

# Standard colors
palette = 0=#000000
palette = 1=#1d28d8
palette = 2=#43c2f4
palette = 3=#6dc4e9
palette = 4=#3f4ce4
palette = 5=#405cf2
palette = 6=#7ea9c3
palette = 7=#bee3eb

# Bright colors
palette = 8=#3c4189
palette = 9=#5f69f1
palette = 10=#95e1fd
palette = 11=#b9e7f9
palette = 12=#8b93f3
palette = 13=#91a1fd
palette = 14=#bcd3e1
palette = 15=#e6e6e6
