$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(64, 92, 242, 1)
$font_color = rgba(230, 230, 230, 1)
$placeholder_color = rgba(230, 230, 230, 0.7)
$check_color = rgba(126, 169, 195, 1)
